# Generated by Django 5.2.4 on 2025-08-03 15:20

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=250)),
                ('recovery_types', models.CharField(choices=[('По приватному ключу', 'By private key'), ('Через файл Keystore + пароль', 'With Keystore file + password'), ('Через резервную копию', 'With backup'), ('С помощью сервиса поддержки', 'With the help of support service')], max_length=250, verbose_name='Тип восстановления')),
                ('wallet_type', models.CharField(choices=[('hardware', 'Аппаратный'), ('software', 'Программный'), ('web', 'Онлайн'), ('mobile', 'Мобильный'), ('exchange', 'Биржевой'), ('paper', 'Бумажный')], default='software', max_length=20, verbose_name='Тип кошелька')),
                ('wallet_volume', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Объем кошелька')),
            ],
            options={
                'db_table': 'Application',
                'ordering': ['id'],
            },
        ),
    ]
