# Generated by Django 5.2.4 on 2025-08-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
